### ISSUE TITLE
Data Profiling (ydata_profiling)

### ISSUE THREAD

**Issue by yukiregista** [yukiregista/DSC_STUDY#3]
Profile data using ydata_profiling.

- [x] Profile report training dataset and upload widget (or html) here
- [x] Add correlation plots as well (if they don't output it)

**Comment by yukiregista** [comment]
They are supposed to output correlations as well but it seems they fail to do it with this dataset...
Maybe we need to output correlation manually

**Comment by yukiregista** [comment]
> They are supposed to output correlations as well but it seems they fail to do it with this dataset... Maybe we need to output correlation manually

Downgrading ydata_profiling to 4.6.2 solved this problem.

**Comment by yukiregista** [comment]
Updates merged into main.

**Comment by sinsukehlab** [comment]
Resolved in #10
